## docker-compose -f docker-compose.build.yml run

version: "3.9"
services:
  test-ubuntu16:
    build:
      target: test
      args:
        - CODE_VERSION=ubuntu16
        - BASE_IMAGE=octopusclients-test
