#nullable enable
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Octopus.Client.Model.Itsm.ServiceNow;

public class ServiceNowIntegrationConnectionResource
{
    public string? Id { get; set; }

    [Description("Enter a name for this connection")]
    [DisplayName("ServiceNow Connection Name")]
    [Required]
    public string? ConnectionName { get; set; }

    [Description("Enter the base url of your ServiceNow instance.")]
    [DisplayName("ServiceNow Base Url")]
    public string? BaseUrl { get; set; }

    [Description("Enter the client id generated by your ServiceNow instance.")]
    [DisplayName("ServiceNow OAuth client id")]
    public string? OAuthClientId { get; set; }

    [Description("Enter the client secret generated by your ServiceNow instance.")]
    [DisplayName("ServiceNow OAuth client secret")]
    public SensitiveValue? OAuthClientSecret { get; set; }

    [Description("Enter the username of your ServiceNow service account user.")]
    [DisplayName("ServiceNow service account user")]
    public string? Username { get; set; }

    [Description("Enter the password of your ServiceNow service account user.")]
    [DisplayName("ServiceNow service account user password")]
    public SensitiveValue? UserPassword { get; set; }
}