namespace Octopus.Client.Model
{
    public enum AutomationEnvironment
    {
        NoneOrUnknown,
        Octopus,
        Bamboo,
        TeamCity,
        AzureDevOps,
        AppVeyor,
        BitBucket,
        Jenkins,
        CircleCI,
        GitLabCI,
        Travis,
        GoCD,
        BitRise,
        Buddy,
        BuildKite,
        CirrusCI,
        AWSCodeBuild,
        Codeship,
        Drone,
        Dsari,
        Hudson,
        MagnumCI,
        SailCI,
        Semaphore,
        Shippable,
        SolanoCI,
        StriderCD,
        GitHubActions
    }
}